### PR TITLE
Group Chat

### PR DESCRIPTION
**Pull request by GoldenWind8**
- Description: Group chat functionality

### CODE REVIEW

**Comment by kyegomez** [comment]
@GoldenWind8 put the groupchat example code in the main groupchat in the root in a file called groupchat.py

**Comment by kyegomez** [comment]
@GoldenWind8 Create tests for this class and add them in the tests folder, and create documentation in the docs/swarms/swarms folder and then add in mkdocs.yml, and add documentation in the docstrings

**Comment by ZackBradshaw** [comment]
Resolved merger conflicts

**Comment by kyegomez** [comment]
@GoldenWind8 submit a fresh pr, this is adding alot of new code that has been deleted!

**Pull request closed without merging**
