### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by jmikedupont2**
dont merge this yet,
just documenting my changes. 

1. the sentry logging seems a bit excessive and privacy invading.
2. adding log traces to see what else is going on.

----
📚 Documentation preview 📚: https://swarms--482.org.readthedocs.build/en/482/

### CODE REVIEW

**Comment by kyegomez** [comment]
@jmikedupont2 is this ready for merging?

**Comment by jmikedupont2** [comment]
No not yet

**Comment by kyegomez** [comment]
@jmikedupont2 let me know I want to accept ASAP

**Comment by jmikedupont2** [comment]
i am busy with other things right now, you will have to wait pls

**Comment by evelynmitchell** [comment]
Hi Mike, have you had a chance to work on this? 
Thanks, Evelyn

**Comment by jmikedupont2** [comment]
This branch could use some attention @patrickbdevaney

**Comment by patrickbdevaney** [comment]
> This branch could use some attention @patrickbdevaney

No problem. How would you like me to work on it? Add me as a contributor to the fork, or for me to make a fork of the forked repo and PR?

**Comment by jmikedupont2** [comment]
we would like to get the docker build going, so publishing docker images
and testing swarms in docker in github actions and then we can use it in
github workspaces or hugging face spaces easily. i think i did work on
getting that going back then.

**Comment by jmikedupont2** [comment]
I am going to rebase this on my other branch and get the docker containers working

**Comment by jmikedupont2** [comment]
I am reworking this into a new pr

**Pull request closed without merging**
