### PR TITLE
three

### PR DESCRIPTION
**Pull request by diegocabello**
simplified documentation, added splash text, will do more later

----
📚 Documentation preview 📚: https://swarms--496.org.readthedocs.build/en/496/

### CODE REVIEW

**Comment by evelynmitchell** [comment]
Is this project using setuptools? I thought it was using poetry.

**Comment by evelynmitchell** [comment]
termcolor was already a requirement, with a pinned version.

**Comment by evelynmitchell** [comment]
The business analyst docs look great.

**Comment by kyegomez** [comment]
@diegocabello what happened to this pr?

**Pull request closed without merging**
