### PR TITLE
CICD cleanup

### PR DESCRIPTION
**Pull request by evelynmitchell**
I've removed duplicate cicd actions.
I've added yamllint to the lint workflow.
I've put yamllint, flake8 and ruff into a single lint workflow.

I've corrected all yaml lint errors.

There is still more to do, but this is a solid start to the cleanup.

### CODE REVIEW

**Comment by kyegomez** [comment]
@evelynmitchell have you ran this? and does it work?

**Comment by evelynmitchell** [comment]
It works better than it did before.

**Comment by kyegomez** [comment]
How do you run the GitHub actions locally without pushing?

**Comment by evelynmitchell** [comment]
I allowed the actions to run on my copy of the repo. I cancelled the python
package build and the docker build.

**Pull request closed without merging**
